# Generated by Django 4.1.13 on 2023-12-02 01:40

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.EmailField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=50)),
                ('semester', models.CharField(max_length=10)),
                ('approve_teacher', models.CharField(blank=True, max_length=100)),
                ('approve_teacher_email', models.EmailField(blank=True, max_length=100)),
                ('user_description', models.TextField(blank=True)),
                ('enrolled_courses', djongo.models.fields.JSONField(blank=True, default=[])),
            ],
        ),
    ]
