# Generated by Django 4.1.13 on 2024-02-01 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.EmailField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=50)),
                ('semester', models.CharField(max_length=10)),
                ('approve_teacher', models.CharField(blank=True, max_length=100)),
                ('approve_teacher_email', models.EmailField(blank=True, max_length=100)),
                ('user_description', models.TextField(blank=True)),
                ('score_teacher', models.FloatField(default=0.0)),
                ('profile_image_url', models.ImageField(blank=True, upload_to='assets/instructorPhotos/')),
                ('enrolled_courses', models.JSONField(blank=True, default=dict)),
                ('email_verification', models.BooleanField(default=False)),
                ('session_token', models.CharField(default='', max_length=300)),
            ],
        ),
    ]
