# Generated by Django 4.1.13 on 2023-12-29 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='score_teacher',
            field=models.FloatField(default=0.0),
        ),
    ]
