# Generated by Django 4.1.13 on 2024-01-07 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_user_profile_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image_url',
            field=models.ImageField(blank=True, upload_to='assets/instructorPhotos/'),
        ),
    ]
