# Generated by Django 4.1.13 on 2023-12-09 22:09

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('instructors', djongo.models.fields.JSONField(blank=True, default=[])),
                ('modules', djongo.models.fields.JSONField(blank=True, default=[])),
                ('comments', djongo.models.fields.JSONField(blank=True, default=[])),
                ('assessment', models.IntegerField()),
                ('publication_course_date', models.CharField(max_length=30)),
            ],
        ),
    ]
