# Generated by Django 4.1.13 on 2024-02-01 00:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('instructor', models.CharField(blank=True, max_length=300)),
                ('modules', models.JSONField(blank=True, default=dict)),
                ('comments', models.JSONField(blank=True, default=dict)),
                ('assessment', models.FloatField(default=0.0)),
                ('trailer_video_url', models.FileField(blank=True, upload_to='assets/coursesVideos/')),
                ('course_image_url', models.ImageField(blank=True, upload_to='assets/coursesPhotos/')),
            ],
        ),
    ]
