# Generated by Django 4.1.13 on 2024-01-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('instructor', models.CharField(blank=True, max_length=300)),
                ('modules', models.JSONField(blank=True, default=dict)),
                ('comments', models.JSONField(blank=True, default=dict)),
                ('assessment', models.FloatField(default=0.0)),
                ('trailer_video_url', models.CharField(max_length=500)),
            ],
        ),
    ]
