import { 
  faLock, 
  faTv, 
  faFloppyDisk, 
  faPlay, 
  faPause, 
  faBagShopping, 
  faPenToSquare, 
  faStopwatch, 
  faCheck, 
  faRightToBracket, 
  faBookOpen,
  faBook,
  faChevronDown,
  faChevronUp,
  faChevronLeft,
  faChevronRight,
  faSearch,
  faUser,
  faUserCircle,
  faRightFromBracket,
  faEnvelope,
  faStar,
  faStarHalfStroke,
  faBolt,
  faBars
 } from '@fortawesome/free-solid-svg-icons';
import { faStar as farStar } from '@fortawesome/free-regular-svg-icons';
import { faGithub, faLinkedinIn } from '@fortawesome/free-brands-svg-icons';

const icons = {
  faGithub,
  faLinkedinIn,
  faLock,
  faTv,
  faBagShopping,
  faPlay,
  faPause,
  faFloppyDisk,
  faPenToSquare,
  faStopwatch,
  faCheck,
  faRightToBracket,
  faBookOpen,
  faBook,
  faChevronDown,
  faChevronUp,
  faChevronLeft,
  faChevronRight,
  faSearch,
  faUser,
  faUserCircle,
  faRightFromBracket,
  faEnvelope,
  faStar,
  farStar,
  faStarHalfStroke,
  faBolt,
  faBars
};

export default icons;