# Generated by Django 4.1.13 on 2023-11-20 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.EmailField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=50)),
                ('semester', models.CharField(max_length=10)),
                ('approve_teacher', models.CharField(blank=True, max_length=100)),
                ('approve_teacher_email', models.EmailField(blank=True, max_length=100)),
                ('user_description', models.TextField(blank=True)),
                ('enrolled_courses', models.JSONField(blank=True, default=dict, null=True)),
            ],
        ),
    ]
